server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      url: ${REDIS_PUBLIC_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    enabled: false

  jwt:
    secret: ${JWT_SECRET:vI9w4eiqMyTbQbwD5891ApcbUPaVlxdH7Sj52co1Dv0=}
    expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntax-highlight:
      activated: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
