server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  datasource:
    # Railway MySQL public endpoint
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:carpooling}?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      # Railway Redis public endpoint
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USER:}
      password: ${REDIS_PASSWORD:}
      # Hoặc dùng thẳng URI nếu muốn:
      # url: ${REDIS_PUBLIC_URL:}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    enabled: false

  jwt:
    secret: ${JWT_SECRET:vI9w4eiqMyTbQbwD5891ApcbUPaVlxdH7Sj52co1Dv0=}
    expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntax-highlight:
      activated: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
